# fly.toml app configuration file generated for abendklang on 2024-02-14T15:32:58+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'abendklang'
primary_region = 'arn'
console_command = 'php /var/www/html/artisan tinker'

[build]
  [build.args]
    NODE_VERSION = '18'
    PHP_VERSION = '8.3'

[env]
  APP_ENV = 'production'
  LOG_CHANNEL = 'stderr'
  LOG_LEVEL = 'info'
  LOG_STDERR_FORMATTER = 'Monolog\Formatter\JsonFormatter'
  SESSION_DRIVER = 'cookie'
  SESSION_SECURE_COOKIE = 'true'
  APP_NAME = 'abendklang'
  APP_URL = 'https://abendklang.linea.studio'
  DB_CONNECTION = 'sqlite'
  DB_DATABASE = '/var/www/html/storage/database/database.sqlite'
  SESSION_LIFETIME= 7200
  SPOTIFY_REDIRECT_URI= 'https://abendklang.linea.studio/auth/callback'


[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1